feat: image manifest capability
kubewarden/policy-sdk-rust pull request #129
Opened 2024-02-01 12:57 UTC by jvanz

## Description

Adds a new capability function to allow users request the OCI image manifest to the given image name.

Fix #128

2024-02-01 13:50 UTC, jvanz commented
@kubewarden/kubewarden-developers I'm trying to add tests to this new function

2024-02-01 16:07 UTC, flavio approved these changes
LGTM, let's try to create a new policy that makes use of that

2024-02-02 19:32 UTC, jvanz commented
Blocked by https://github.com/kubewarden/policy-evaluator/pull/429#issuecomment-1924541219

2024-02-06 13:53 UTC, jvanz commented
> LGTM, let's try to create a new policy that makes use of that

https://github.com/kubewarden/policy-server/issues/638#issuecomment-1924482913

2024-02-07 15:16 UTC, flavio requested changes

2024-02-07 15:16 UTC, flavio commented on src/host_capabilities/verification.rs
> +            println!("verification host_call");
this has to be dropped

2024-02-07 16:41 UTC, jvanz commented on src/host_capabilities/oci.rs
> +                assert_eq!(config.size(), 7023);
Indeed, I've simplified the code by comparing the whole objects.

2024-02-08 13:50 UTC, viccuad approved these changes
LGTM!

2024-02-08 15:10 UTC, fabriziosestito commented on src/host_capabilities/oci.rs
> +            let manifest = DescriptorBuilder::default()
nit: this let bining is not necessary, you could return directly

2024-02-08 15:10 UTC, fabriziosestito approved these changes

2024-02-09 12:06 UTC, merged