feat: Add callbacks for verification of GHA signatures
kubewarden/policy-sdk-rust pull request #46
Opened 2022-06-24 11:13 UTC by viccuad

## Description

Add new API:
  `pub CallbackRequestType::SigstoreGithubActionsVerify{}`
  `pub fn verify_keyless_github_actions()`

Consumers of the SDK can levarage this new API call to ask for
verification of signatures done with jobs in Github Actions.

This API addition is leveraged by policy-evaluator to perform the
callbacks in the wasm host.

Fix https://github.com/kubewarden/policy-sdk-rust/issues/41

## Test

## Additional Information

### Tradeoff

### Potential improvement

2022-06-24 12:00 UTC, flavio requested changes

2022-07-04 07:56 UTC, raulcabello approved these changes
LGTM

2022-07-04 11:41 UTC, jvanz approved these changes

2022-07-04 14:34 UTC, raulcabello approved these changes

2022-07-05 09:04 UTC, flavio commented on src/host_capabilities/mod.rs
> +    SigstoreKeylessPrefixVerify {
nitpicking, add a short description of this struct

2022-07-05 09:07 UTC, flavio requested changes
LGTM, I left some minor changes

2022-07-05 09:07 UTC, flavio commented on src/host_capabilities/mod.rs
> +    SigstoreGithubActionsVerify {
nitpicking, add a short description of this struct

2022-07-05 09:07 UTC, flavio commented on src/host_capabilities/verification.rs
> +/// subject string is streated as a URL prefix, and sanitized to a valid URL on
```suggestion
/// subject string is treated as a URL prefix, and sanitized to a valid URL on
```

2022-07-05 09:07 UTC, flavio commented on src/host_capabilities/verification.rs
> +/// itself by appending `\` to prevent typosquatting. Then, the provided subject
```suggestion
/// itself by appending `/` to prevent typosquatting. Then, the provided subject
```

URLs end with `/`, not `\`

2022-07-05 10:28 UTC, merged

2022-07-05 10:30 UTC, viccuad commented
sigh, sorry, github played games with me and didn't update the page with the new review until I clicked merge.. I will fix it in a follow-up PR, it also needs a version bump to consume on evaluator.